[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "24"
  NEXT_PUBLIC_API_URL = "https://tusventasbackend.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
